apiVersion: v1
kind: ConfigMap
metadata:
  name: config-kub-values
data:
  DATABASE_URL: <DATABASE_URL>
  POSTGRES_DB: <POSTGRES_DB>
  POSTGRES_USER: <POSTGRES_USER>

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-kb-values
type: Opaque
data:
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD_BASE64>
  DATABASE_PASSWORD: <DATABASE_PASSWORD_BASE64>
